# curl -X POST http://localhost:8080/create -H "Content-Type: application/json" -d '{
#     "shortCode": "abc123",
#     "originalUrl": "https://example.com"
# }'

### Create a new short URL
POST /create
Content-Type: application/json
Host: localhost:8080

{
    "shortCode": "wow300",
    "originalUrl": "https://wow.com",
    "userId": 123
}

### Get the original URL for a short URL
GET /get/abc100
Host: localhost:8080

### Get urls by user
GET /geturls/123
Host: localhost:8080